<a href="https://colab.research.google.com/github/abhiraman/Capstone_Project/blob/main/Algorithms/logistic_regression_from_scratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import sklearn
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

In [69]:
def sigmoid_fn(feature_vector,wt_vector,bias):
  z = np.dot(feature_vector,wt_vector)+bias
  #z = np.sum((total,np.ones(total.shape)*bias),axis=0)
  return 1/(1+np.exp(-z))


In [70]:
def gradient(y_pred,y,feature_vec):
  del_w = (y_pred-y)*feature_vec
  del_b = (y_pred-y)
  return del_w,del_b       ## shape as shape as input vector (# of features)


In [19]:
def bce_loss(y_pred,y):
  return -((1-y)*np.log(1-y_pred)+(y*np.log(y_pred)))

In [71]:
def intialize_params(wt_size):
  ## 1D Convolution ##
  wts = np.random.randn(wt_size)
  bias = np.random.randn(1,)
  return wts,bias



In [34]:
def accuracy(y_pred,y):
  right = 0
  for i,j in zip(y_pred,y):
    if i==j:right+=1
  return (right/len(y_pred))*100

In [93]:
def fit(input,target,epochs,lr=0.05):

  wt,b = intialize_params(input.shape[1])
  max_loss = 100000
  
  final_wt,final_bias = None,None
  for i in range(epochs):
    dw,db = 0,0
    all_result = []
    loss = 0
    for inp,targ in zip(input,target):
      y_pred = sigmoid_fn(inp,wt,b)
      loss += bce_loss(y_pred,targ)
      dw,db = gradient(y_pred,targ,inp)
      
      dw +=dw
      db+=db
      if y_pred>0.5: all_result.append(1)
      else: all_result.append(0)

      #if i%10==0:
      wt -= dw*lr
      b-=db*lr
    if i%10==0:
      print("Loss {} after {} Epochs".format(loss/len(input),i))
      print("Training Accuracy : {}".format(accuracy(all_result,target.tolist())))
    if loss<max_loss:
      final_wt = wt
      final_bias = b
  return final_wt,final_bias

    

In [77]:
from sklearn.datasets import make_classification

In [89]:
X, y = make_classification(
        n_samples=10, 
        n_features=2,
        n_redundant=0,
        n_informative=2,
        random_state=1, 
        n_clusters_per_class=1)
print(X)
print(y)

[[-0.64185521  0.78535215]
 [ 0.10972634  1.83671408]
 [-1.07362634  2.591487  ]
 [-1.38222372  0.85340843]
 [ 1.78689446  2.3841826 ]
 [ 0.94785273  3.53015683]
 [ 1.08876018  1.35925144]
 [ 0.42774158  3.54015499]
 [-0.88398194 -0.57876171]
 [-1.59347411  1.2168913 ]]
[1 0 1 1 0 0 0 0 1 1]


In [94]:
fit(X,y,100)

Loss [0.46363044] after 0 Epochs
Training Accuracy : 90.0
Loss [0.13019358] after 10 Epochs
Training Accuracy : 100.0
Loss [0.0867915] after 20 Epochs
Training Accuracy : 100.0
Loss [0.06742005] after 30 Epochs
Training Accuracy : 100.0
Loss [0.05594254] after 40 Epochs
Training Accuracy : 100.0
Loss [0.04816906] after 50 Epochs
Training Accuracy : 100.0
Loss [0.04247809] after 60 Epochs
Training Accuracy : 100.0
Loss [0.03809408] after 70 Epochs
Training Accuracy : 100.0
Loss [0.0345933] after 80 Epochs
Training Accuracy : 100.0
Loss [0.03172194] after 90 Epochs
Training Accuracy : 100.0


(array([-4.5500594 , -1.23318181]), array([0.88358081]))